#!/bin/sh
# Copyright 2002 - Robert M. Pufky
# Configuration script for pictureframe

# Verify we are running as root and can install things
if [ `whoami` != "root" ]; then
  echo "Error: script must be run from root account or sudo"
fi

# Setup installation directories
echo -e -n "Setting up installation directories: "
if [ ! -d /etc/pictureframe ]; then
  `mkdir /etc/pictureframe 2>&1 > /dev/null`
fi
if [ ! -d /usr/local/images ]; then
  `mkdir /usr/local/images 2>&1 > /dev/null`
fi
if [ ! -d /usr/local/originals ]; then
  `mkdir /usr/local/originals 2>&1 > /dev/null`
fi
echo "done."

# Copy configuration files to install directories
echo -e -n "Setting up pictureframe files: "
`cp -f config.php /etc/pictureframe/ 2>&1 > /dev/null; cp -f convertengine.php /usr/local/bin/ 2>&1 > /dev/null; cp -f displayengine.php /usr/local/bin/ 2>&1 > /dev/null; cp -f pictureframe /etc/init.d/ 2>&1 > /dev/null`
echo "done."

# Verify permissions
echo -e -n "Verifying file permissions: "
`chmod 644 /etc/pictureframe/config.php 2>&1 > /dev/null; chmod 755 /usr/local/bin/* 2>&1 > /dev/null; chmod 755 /etc/init.d/pictureframe 2>&1 > /dev/null; chmod o+w /usr/local/originals 2>&1 > /dev/null`
echo "done."

# Install required packages
echo -e -n "Upgrading system to latest patches: "
`apt-get -qq update 2>&1 > /dev/null; apt-get -qq upgrade 2>&1 > /dev/null`
echo "done."
echo -e -n "Installing packages required for pictureframe: "
`apt-get -qq install php4-cli xloadimage imagemagick unclutter 2>&1 > /dev/null`
echo "done."
echo -e -n "Disabling common X display managers: "
`update-rc.d -f xdm remove 2>&1 > /dev/null`
`update-rc.d -f gdm remove 2>&1 > /dev/null`
`update-rc.d -f kdm remove 2>&1 > /dev/null`
echo "done."

# Configure php4-cli (and make backup file)
echo -e -n "Configuring php cli for pictureframe: "
`sed -i.bak "s/max_execution_time\ =\ 30/max_execution_time\ =\ 0/g" /etc/php4/cli/php.ini`
`sed -i "s/memory_limit\ =\ 8M/memory_limit\ =\ 100M/g" /etc/php4/cli/php.ini`
echo "done."

# Configure pictureframe to startup as a service
echo -e -n "Configuring pictureframe service: "
`update-rc.d -f picturefram remove 2>&1 > /dev/null`
`update-rc.d -f pictureframe start 99 2 . stop 99 1 3 4 5 6 S . 2>&1 > /dev/null`
echo "done."

# Configure 'picture' user and prompt for password
echo -e -n "Configuring 'picture' user: "
if [ ! -d /home/picture ]; then
  echo -e -n "\n'picture' user not found!  -- Creating NEW 'picture' user:\n\n"
  adduser picture
else
  echo -e -n "'picture' user already exists! "
fi
echo "done."

# Link to pictures directory
echo -e -n "Verifying link to pictures directory: "
if [ ! -d /home/picture/pictures ]; then
  `ln -sf /usr/local/originals /home/picture/pictures`
fi
echo "done."
echo -e "\nDone!  Please verify configuration before rebooting!\n"
