#!/bin/sh
# Copyright 2002 - Robert M. Pufky
# Configuration script for pictureframe

# Verify we are running as root and can install things
if [ `whoami` != "root" ]; then
  echo "Error: script must be run from root account or sudo"
fi

# Setup installation directories
echo -e -n "Setting up installation directories: "
if [ ! -d /etc/pictureframe ]; then
  `mkdir /etc/pictureframe > /dev/null 2>&1`
fi
if [ ! -d /usr/local/images ]; then
  `mkdir /usr/local/images > /dev/null 2>&1`
fi
if [ ! -d /usr/local/originals ]; then
  `mkdir /usr/local/originals > /dev/null 2>&1`
fi
echo "done."

# Copy configuration files to install directories
echo -e -n "Setting up pictureframe files: "
`cp -f config.php /etc/pictureframe/ > /dev/null 2>&1; cp -f convertengine.php /usr/local/bin/ > /dev/null 2>&1; cp -f displayengine.php /usr/local/bin/ > /dev/null 2>&1; cp -f pictureframe /etc/init.d/ > /dev/null 2>&1`
echo "done."

# Verify permissions
echo -e -n "Verifying file permissions: "
`chmod 644 /etc/pictureframe/config.php > /dev/null 2>&1; chmod 755 /usr/local/bin/* > /dev/null 2>&1; chmod 755 /etc/init.d/pictureframe > /dev/null 2>&1; chmod o+w /usr/local/originals > /dev/null 2>&1`
echo "done."

# Install required packages
echo -e -n "Upgrading system to latest patches: "
`apt-get -y update; apt-get -y upgrade`
echo "done."
echo -e -n "Installing packages required for pictureframe: "
`apt-get -y install php4-cli xloadimage imagemagick unclutter`
clear
echo "Upgrading system to latest patches: done."
echo -e -n "Disabling common X display managers: "
`rm -f /etc/rc?.d/???xdm > /dev/null 2>&1`
`rm -f /etc/rc?.d/???gdm > /dev/null 2>&1`
`rm -f /etc/rc?.d/???kdm > /dev/null 2>&1`
echo "done."

# Configure php4-cli (and make backup file)
echo -e -n "Configuring php cli for pictureframe: "
`sed -i.bak "s/max_execution_time\ =\ 30/max_execution_time\ =\ 0/g" /etc/php4/cli/php.ini`
`sed -i "s/memory_limit\ =\ 8M/memory_limit\ =\ 100M/g" /etc/php4/cli/php.ini`
echo "done."

# Configure pictureframe to startup as a service
echo -e -n "Configuring pictureframe service: "
`rm -f /etc/rc?.d/???pictureframe > /dev/null 2>&1`
`update-rc.d -f pictureframe start 99 2 . stop 99 1 3 4 5 6 S . > /dev/null 2>&1`
echo "done."

# Configure 'picture' user and prompt for password
echo -e -n "Configuring 'picture' user: "
if [ ! -d /home/picture ]; then
  echo -e -n "\n'picture' user not found!  -- Creating NEW 'picture' user:\n\n"
  adduser picture
else
  echo -e -n "'picture' user already exists! "
fi
echo "done."

# Link to pictures directory
echo -e -n "Verifying link to pictures directory: "
if [ ! -d /home/picture/pictures ]; then
  `ln -sf /usr/local/originals /home/picture/pictures > /dev/null 2>&1`
fi
echo "done."
echo -e "\nDone!  Please verify configuration before rebooting!\n"
